version: '3.7'
services:
  maven:
    image: app
    container_name: maven
    ports:
     - 8080:8080
    networks:
     - mynet
    depends_on:
      database:
        condition: service_healthy
#    volumes:
#     - build4:/app/src/main/webapp
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 5

  database:
    image: mysql:5.7
    container_name: database
    ports:
     - 3306:3306
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:3306"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
     - mynet
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lavagna
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
     - volume:/var/lib/mysql/

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
     - 8082:80
    environment:
     - NGINX_PORT=80
    networks:
     - mynet
    depends_on:
      maven:
        condition: service_healthy
    volumes:
     - ./src/main/webapp:/usr/share/nginx/html
     - ./conf/nginx.conf:/etc/nginx/nginx.conf
#     - ./index.html:/usr/share/nginx/html/index.html

networks:
  mynet:
    name: mynet

volumes:
  volume:
    name: volume
#  build4:
#    name: build4
